# Generated by Django 2.2.1 on 2019-05-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.CharField(default='http://placekitten.com/100/150', max_length=300),
        ),
    ]
