# Generated by Django 2.2.1 on 2019-05-22 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petfinder', '0002_pet_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='id',
            new_name='animal_id',
        ),
    ]
